name: Release

on:
  workflow_dispatch:
    inputs:
      package:
        description: 'Package'
        required: true
        type: choice
        options:
          - react
          - solid
          - vue
      increment:
        description: 'Increment'
        required: true
        default: 'patch'
        type: choice
        options:
          - major
          - minor
          - patch
      isPreRelease:
        description: 'Pre-Release'
        required: true
        default: true
        type: boolean

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Branch
        uses: actions/checkout@v3

      - name: Setup Git User
        shell: bash
        run: |
          git config --global user.name "$(git --no-pager log --format=format:'%an' -n 1)"
          git config --global user.email "$(git --no-pager log --format=format:'%ae' -n 1)"

      - name: Setup pnpm
        uses: pnpm/action-setup@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          registry-url: 'https://registry.npmjs.org'
          cache: 'pnpm'

      - name: Install
        run: pnpm install

      - name: Build
        run: pnpm ${{ github.event.inputs.package }} build

      - name: Pre-Release
        if: github.event.inputs.isPreRelease == 'true'
        # run: pnpm ${{ github.event.inputs.package }} release-it pre${{ github.event.inputs.increment }} --ci --preRelease=beta
        run: pnpm ${{ github.event.inputs.package }} release-it --preRelease
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

      - name: Release
        if: github.event.inputs.isPreRelease == 'false'
        run: pnpm ${{ github.event.inputs.package }} release-it --ci --increment ${{ github.event.inputs.increment }}
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

      # TODO Trigger notification when new website is deployed
      # - name: Notification
      #   uses: slackapi/slack-github-action@v1.24.0
      #   with:
      #     payload: |
      #       {
      #         "package_name": "${{ github.event.inputs.package }}",
      #         "changelog_url": "https://ark-ui.com/docs/${{ github.event.inputs.package }}/overview/changelog"
      #       }
      #   env:
      #     SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
